#version: '3'

services:

  plex-mount:
    #image: pknw1/pfs:final
    build: .
    container_name: plex-mount
    user: 0:0
    restart: always
    hostname: plex-mount
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp:/tmp
      - ./config.json:/app/config.json
      - /mnt/RS:/mnt:rshared
    environment:
      - USER=root
      - TZ=Europe/London
      - PUID=0
      - PGID=0
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
